name: All Contributors

on:
  issue_comment:
    types: [created]

permissions: read-all

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: >
      github.event.issue.pull_request == null &&
      contains(github.event.comment.body, '@all-contributors please add')
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450  # v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v6

      - name: Add contributor
        uses: all-contributors/all-contributors-action@b8a138346bb95814b4a1c25dec9bfd61f15e7fa4  # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
