name: All Contributors

on:
  issue_comment:
    types: [created]

permissions: read-all

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: >
      github.event.issue.pull_request == null &&
      contains(github.event.comment.body, '@all-contributors please add')
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40  # v2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6

      - name: Add contributor
        uses: all-contributors/all-contributors-action@b8a138346bb95814b4a1c25dec9bfd61f15e7fa4  # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
